addons:
  postgresql: 9.6
before_script:
  - psql -c 'create database yart_test;' -U postgres
language: ruby
rvm:
  - 2.4.2
script:
  - bin/rails db:migrate RAILS_ENV=test
  - yarn install
  - bundle exec rubocop
  - bundle exec rspec