addons:
  postgresql: 9.6
before_script:
- psql -c 'create database yart_test;' -U postgres
language: ruby
rvm:
- 2.4.2
script:
- bin/rails db:migrate RAILS_ENV=test
- yarn install
- bundle exec rubocop
- bundle exec rspec
- yarn install
deploy:
  provider: heroku
  api_key:
    secure: n+Dx2741w+4ytTf86S8nMJNfEBTFpqCClx69vFUfNkqRDJpxwu+LCX1fYyWylZSzmkN+DcPMmWZs7UIfYPkuhxyOfEfCmOt+/Vb3doBOdoERR4U37z8BOoKOj++yDwfjXwnRvsx+qjhlOL66aACb/cL7zzATBSScQRkJcQqTuf14XzyNxGAaSxuludjgZJHGSTMCOftOvALH96uR42rcrg/vRkTiLgpJoQ7qMyouOcJFQikNhS6L5ZNhxZJNnx8pZQlQ3Qi7xY9CltouWw8vX/fnnk3O167LZ1e10pxeT1fmayzS6/4EnI2gwyWi1ek4dkVOyEhEf08qlDK21MW5p3uNLNu3cOUBhsVGQSZ8ivxl9e0pG7AHH8mXHoL8ve1OOIyD2QXIbaqyOJE+N6SonA2Z7uI8DS0W1Dlp4RAi1xDHIiwnomESSaxWx3xRFbD/e+ejSw4alIKqJ6Ip8L//pH5Qy0rRNphxAM5A9V5nZe77vByQVfeafXv8Q0gQZzWrVOF3cu0NFc37+Q1+NY6oiNPyWNWNjsyVs3qc5olPYQ5/vuYcT0VdEir0S1snW8M0dBxq9gyxywy41Fhun6Pf78u4D81+VW0mH+Rmi3a61foqUYAgfVnyeAo0TPqsmx6XofXHnvx4YtQZdhGYaw6QXg6gw6SpdVuNeR7JpCWvU/k=
  app: yartapp
  on:
    repo: EhsanZ/yart
