addons:
  postgresql: 9.6
before_script:
  - psql -c 'create database yart_test;' -U postgres
language: ruby
rvm:
  - 2.4.2
script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec